### ISSUE TITLE
Consider removing appveyor.yml file

### ISSUE THREAD

**Issue by jorgepiloto** [pyvista/pytest-pyvista#10]
🐞 **Problem**
the `appveyor.yml` file got generated as a consequence of the cookiecutter template. This file is used to configure the CI/CD in the Appveyor platform. However, it looks like this repository takes advantage of GitHub actions for CI/CD purposes. Therefore, it looks like this file is no longer needed.

**Comment by jorgepiloto** [comment]
Pinging here @AlejandroFernandezLuces for visibility.

**Comment by RobPasMue** [comment]
Same happens with the badge added to the README.rst file. The one for appveyor is also not needed.

**Comment by AlejandroFernandezLuces** [comment]
Thank you for noticing! I'll do it as soon as I can.

**Comment by AlejandroFernandezLuces** [comment]
Closed in #33 and in commit b02006b16790498ee1d96d018cc95a9b5cef8727
