### ISSUE TITLE
Default cache_dir value could be better?

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pytest-pyvista#16]
IMO, this default value is not the best choice:

https://github.com/pyvista/pytest-pyvista/blob/374c284d67c962bdb516a77e661f415c30011b47/pytest_pyvista/pytest_pyvista.py#L88-L89

I'd like to request some clarification on this choice and propose altering it to use the current working directory.

I would expect `pytest .`  to properly handle the image cache or default to save the cache in a location that is visible/relative to the active project. This current default dumps the images in a non-visible location.

An alternative option is to have `cache_dir` be easily stable in the `conftest.py` for a project -- is this currently possible?

**Comment by adeak** [comment]
As someone who only understands what's going on due to slack: the current default means that the image cache included in the repo is not used at all unless it's explicitly requested with a command-line argument. So just running `pytest` locally silently ignores the image cache, is what we probably never want to be the default.

**Comment by banesullivan** [comment]
Precisely. Thank you for clarifying, @adeak

**Comment by banesullivan** [comment]
cc @pyvista/developers

**Comment by MatthewFlamm** [comment]
I think there should not be a default at all for where the cached images are, it should be a required user setting. We should have a default directory for where new images are placed and compared to the cached images.  As in the suggestions here:

https://github.com/pyvista/pytest-pyvista/pull/3#discussion_r1019650824

**Comment by adeak** [comment]
Sounds like that would also fix https://github.com/pyvista/pytest-pyvista/issues/17 @MatthewFlamm.
