### ISSUE TITLE
Not creating images for new tests

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pytest-pyvista#17]
The old behavior was that if the image was missing, it would be created. Now you have to use `--reset_image_cache` to generate figures for new tests.

Can we make it so that if the cached image is missing, it gets generated?

**Comment by MatthewFlamm** [comment]
I think that we should store _all_ generated images in a separate dir, defaulted to a temporary dir.  Then we can also compare subtle differences too.

I need to get out of the bad habit of suggesting ideas on other issues that are linked.
