### ISSUE TITLE
Release 0.1.9

### ISSUE THREAD

**Issue by AlejandroFernandezLuces** [pyvista/pytest-pyvista#86]
Hi @pyvista/maintainers, pinging @germa89 for visibility.

I was wondering if I could make a release for the plugin, since we need to use the new flag introduced in #82 

If that's okay, I will proceed.

**Comment by MatthewFlamm** [comment]
Should we also get #80 in there?

**Comment by AlejandroFernandezLuces** [comment]
Yes, that's a good idea! Let's merge that first

**Comment by germa89** [comment]
#80 is ready to merge (once green check blessing)

**Comment by germa89** [comment]
We should include also https://github.com/pyvista/pytest-pyvista/pull/87

**Comment by MatthewFlamm** [comment]
I think we are all set.  Thanks all!

**Comment by tkoyama010** [comment]
Close as it is released.
